
---
spring:
  profiles: cloud
  datasource:
    druid:
      web-stat-filter:
        enabled: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/t_oauth
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:1qaz!QAZ}
    testWhileIdle: true
    validationQuery: SELECT 1
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    loadbalancer:
      retry:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
